#!/bin/sh

echo 'Install Spectacle: https://www.spectacleapp.com/'
echo ''
echo 'To move a window between multiple monitors: CTRL-OPTION-CMD-<LEFT/RIGHT>'
echo ''
echo 'To minimize a window: CMD-M'
echo ''
echo 'To full-screen-toggle a window: OPTION-CMD-F'
echo ''
echo 'To restore a window: CMD-TAB to the app, press OPTION and keep pressed, release CMD'
echo ''
echo 'To move a window into sides: OPTION-CMD-<UP/DOWN/LEFT/RIGHT>'
echo ''
echo 'To move a window into upper corners: CTRL-CMD-<LEFT/RIGHT>'
echo ''
echo 'To move a window into lower corners: SHIFT-CTRL-CMD-<LEFT/RIGHT>'
echo ''
echo 'To center a window: OPTION-CMD-C'
