@echo off
rem Generated by JetBrains Toolbox 1.22.10970 at 2021-12-18T19:52:20.987352900

set waitarg=
set ideargs=

:next
set "passwait="
if "%~1"=="--wait" set passwait=1
if "%~1"=="-w" set passwait=1
if defined passwait (set waitarg=/wait)
if not "%~1"=="" (
  if defined passwait (set "ideargs=%ideargs%--wait ") else (set "ideargs=%ideargs%%1 ")
  shift
  goto next
)

start "" %waitarg% C:\Users\rubin\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\213.5744.248\bin\pycharm64.exe %ideargs%