@echo off
rem Generated by JetBrains Toolbox 1.24.11947 at 2022-05-05T12:19:12.650466900

set waitarg=
set ideargs=

:next
set "passwait="
if "%~1"=="--wait" set passwait=1
if "%~1"=="-w" set passwait=1
if defined passwait (set waitarg=/wait)
if not "%~1"=="" (
  if defined passwait (set "ideargs=%ideargs%--wait ") else (set "ideargs=%ideargs%%1 ")
  shift
  goto next
)

start "" %waitarg% C:\Users\rubin\AppData\Local\JetBrains\Toolbox\apps\Rider\ch-0\221.5591.20\bin\rider64.exe %ideargs%